name: Build and Deploy
on:
  push:
    branches:
      - 'master'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: trzeci/emscripten:1.39.4-ubuntu

    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: ğŸ§° Installing Tools
        run: |
          apt-get update && apt-get install -y ninja-build rsync
          wget https://github.com/Kitware/CMake/releases/download/v3.17.0/cmake-3.17.0.tar.gz
          tar -xzf cmake-3.17.0.tar.gz
          cd cmake-3.17.0/
          ./configure
          make
          make install
          update-alternatives --install /usr/bin/cmake cmake /usr/local/bin/cmake 1 --force
          cmake --version

      - name: ğŸ”§ Configure
        run: cmake -Bbuild . -GNinja -DPLATFORM=Web -DCMAKE_TOOLCHAIN_FILE=$EMSCRIPTEN/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_VERBOSE_MAKEFILE=ON

      - name: â›ï¸ Build 
        run: cmake --build build

      - name: ğŸš€ Deploy 
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/bin # The folder the action should deploy.